# Generated by Django 2.2a1 on 2019-04-07 18:39

import Letter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=Letter.models.user_directory_path),
        ),
    ]
