# Generated by Django 2.2a1 on 2019-04-07 19:41

import Letter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Letter', '0003_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
	migrations.AlterField(
	    model_name='document',
	    name='document',
	    field=models.FileField(upload_to=Letter.models.user_directory_path),
	),
    ]
