# Generated by Django 2.2a1 on 2019-04-14 19:10

import Letter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Letter', '0005_letter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorpreferences',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
