# Generated by Django 2.2a1 on 2019-04-15 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0009_auto_20190415_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_initiated',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date'),
        ),
    ]
