# Generated by Django 2.2a1 on 2019-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0010_auto_20190415_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
