# Generated by Django 2.2 on 2019-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufileid', models.IntegerField()),
                ('stuid', models.IntegerField()),
                ('requirement', models.CharField(max_length=100)),
                ('teafileid', models.IntegerField()),
                ('teaid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
            ],
        ),
    ]
