# Generated by Django 2.2 on 2019-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='feedback',
            field=models.CharField(default='', max_length=100),
        ),
    ]
