# Generated by Django 2.2 on 2019-04-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0002_content_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='stufileid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='teafileid',
            field=models.IntegerField(null=True),
        ),
    ]
