# Generated by Django 2.2 on 2019-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0003_auto_20190413_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
